language: php

sudo: false

php:
  - 7.0
  - 7.1
  - 7.2

matrix:
  allow_failures:
    - php: 7.2

cache:
  directories:
    - $HOME/.composer/cache

script:
  - ./vendor/bin/phpspec run --format=dot