#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use DI\ContainerBuilder;

$builder = new ContainerBuilder();
$builder->addDefinitions(__DIR__.'/app/config.php');
$container = $builder->build();

$application = $container->get('application');
$application->run();
